AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Create an ECS cluster with an auto scale group and launch config definitions. Both
  the AWS docker AMI and Rancher OS AMI are supported.

Parameters:
  AMIType:
    Type: String
    AllowedValues:
      - Amazon
      - Rancher
    Default:
      Amazon
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the ECS instances.
  DesiredCapacity:
    Type: Number
    Default: '2'
    Description: Number of instances to launch in your ECS cluster.
  MaxSize:
    Type: Number
    Default: '2'
    Description: Maximum number of instances that can be launched in your ECS cluster.
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues: [t2.micro, t2.small, t2.medium, t2.large, m3.medium, m3.large,
      m3.xlarge, m3.2xlarge, m4.large, m4.xlarge, m4.2xlarge, m4.4xlarge, m4.10xlarge,
      c4.large, c4.xlarge, c4.2xlarge, c4.4xlarge, c4.8xlarge, c3.large, c3.xlarge,
      c3.2xlarge, c3.4xlarge, c3.8xlarge, r3.large, r3.xlarge, r3.2xlarge, r3.4xlarge,
      r3.8xlarge, i2.xlarge, i2.2xlarge, i2.4xlarge, i2.8xlarge]
    ConstraintDescription: Please choose a valid instance type.

  EcsClusterName:
    Type: String
    Description: >
      Specifies the ECS Cluster Name with which the resources would be
      associated
    Default: clustah

  EcsRoleName:
    Type: String

  ParameterStoreEnvPath:
    Type: String

  KeyId:
    Type: String

  PrivateSubnet1:
    Type: String

  PrivateSubnet2:
    Type: String

  VpcId:
    Type: String 

  IngressSecurityGroup:
    Description: VPC SSH Ingress Security Group
    Type: String

Mappings:
  AWSRegionToAMI:
    us-east-1:
      AMIID: ami-04351e12
    us-east-2:
      AMIID: ami-207b5a45
    us-west-1:
      AMIID: ami-7d664a1d
    us-west-2:
      AMIID: ami-57d9cd2e
    eu-west-1:
      AMIID: ami-809f84e6
    eu-west-2:
      AMIID: ami-ff15039b
    eu-central-1:
      AMIID: ami-a3a006cc
    ap-northeast-1:
      AMIID: ami-e4657283
    ap-southeast-1:
      AMIID: ami-19f7787a
    ap-southeast-2:
      AMIID: ami-42e9f921
    ca-central-1:
      AMIID: ami-3da81759

# Rancher AMIs via https://github.com/rancher/os/blob/master/README.md
  RancherRegionToAMI:
    us-east-1:
      AMIID: ami-3a71472c
    us-east-2:
      AMIID: ami-51466734
    us-west-1:
      AMIID: ami-b70f23d7
    us-west-2:
      AMIID: ami-3ad2c543
    eu-west-1:
      AMIID: ami-66b2a800
    eu-west-2:
      AMIID: ami-f4041290
    eu-central-1:
      AMIID: ami-f653f599
    ap-northeast-1:
      AMIID: ami-32b1a755
    ap-southeast-1:
      AMIID: ami-d79618b4
    ap-southeast-2:
      AMIID: ami-7d4a591e
    ca-central-1:
      AMIID: ami-cca619a8



Conditions:
  UseAmazonAMI: !Equals [!Ref AMIType, Amazon]

Resources:

  MyCluster:
    Type: "AWS::ECS::Cluster"
    Properties:
        ClusterName: !Ref EcsClusterName

  ServicePolicy:
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: "enableSSM"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: ['ssm:DescribeParameters']
            Resource: '*'
          - Effect: Allow
            Action: ['ssm:Get*']
            Resource:
            - !Join [ "", [ "arn:aws:ssm:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ":parameter", !Ref ParameterStoreEnvPath] ]
            - !Join [ "", [ "arn:aws:ssm:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ":parameter", !Ref ParameterStoreEnvPath, "/*"] ]
          - Effect: Allow
            Action: ['kms:Decrypt']
            Resource: !Join [ "", [ "arn:aws:kms:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ":key/", !Ref KeyId] ]
      Roles: 
        - 
          Ref: "EcsRoleName"

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    DependsOn: ServicePolicy
    Properties:
      Path: /
      Roles: [!Ref 'EcsRoleName']

  EcsInstanceLc:
    Type: AWS::AutoScaling::LaunchConfiguration
    DependsOn: EC2InstanceProfile
    Properties:
      ImageId: !If [UseAmazonAMI, !FindInMap [AWSRegionToAMI, !Ref 'AWS::Region', AMIID], !FindInMap [RancherRegionToAMI, !Ref 'AWS::Region', AMIID]]
      InstanceType: !Ref InstanceType
      AssociatePublicIpAddress: true
      IamInstanceProfile: !Ref EC2InstanceProfile
      KeyName: !Ref KeyName
      SecurityGroups: [ !Ref IngressSecurityGroup ]
      UserData:
        !If
          - UseAmazonAMI
          - Fn::Base64: !Sub |
              #!/bin/bash
              echo ECS_CLUSTER=${EcsClusterName} >> /etc/ecs/ecs.config
          - Fn::Base64: !Sub |
              #cloud-config
              rancher:
                environment:
                  ECS_CLUSTER: ${EcsClusterName}
                  # Note: You will need to add this variable, if using awslogs for ECS task.
                  ECS_AVAILABLE_LOGGING_DRIVERS: |-
                    ["json-file","awslogs"]



  EcsInstanceAsg:
    Type: AWS::AutoScaling::AutoScalingGroup
    DependsOn: MyCluster
    Properties:
      VPCZoneIdentifier:
      - !Ref PrivateSubnet1
      - !Ref PrivateSubnet2
      LaunchConfigurationName: !Ref EcsInstanceLc
      MinSize: '2'
      MaxSize: !Ref MaxSize
      DesiredCapacity: !Ref DesiredCapacity
      Tags:
        -
          Key: Name
          Value: !Sub "ECS Instance - ${AWS::StackName}"
          PropagateAtLaunch: 'true'
        -
          Key: Description
          Value: >
            This instance is the part of the Auto Scaling group which was created
            through ECS Console
          PropagateAtLaunch: 'true'

  ScaleECSClusterOut:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: PercentChangeInCapacity
      PolicyType: StepScaling
      StepAdjustments:
      - ScalingAdjustment: 100
        MetricIntervalLowerBound: 0.0
      AutoScalingGroupName:
        Ref: EcsInstanceAsg

  ScaleECSClusterIn:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: PercentChangeInCapacity
      PolicyType: StepScaling
      StepAdjustments:
      - ScalingAdjustment: -50
        MetricIntervalUpperBound: 0.0
      AutoScalingGroupName:
        Ref: EcsInstanceAsg

  ECSClusterScaleInAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: True
      ComparisonOperator: LessThanOrEqualToThreshold
      EvaluationPeriods: 1
      MetricName: CPUReservation
      Namespace: AWS/ECS
      Period: 300
      Statistic: Average
      Threshold: 25
      AlarmActions:
      - Ref: ScaleECSClusterIn
      Dimensions:
      - Name: ClusterName
        Value: !Ref EcsClusterName

  ECSClusterScaleOutAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: True
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      MetricName: CPUReservation
      Namespace: AWS/ECS
      Period: 300
      Statistic: Average
      Threshold: 75
      AlarmActions:
      - Ref: ScaleECSClusterOut
      Dimensions:
      - Name: ClusterName
        Value: !Ref EcsClusterName

Outputs:

  ECSCluster:
    Value: !Ref MyCluster

